# refs https://docs.travis-ci.com/user/docker/
sudo: required

services:
  - docker

before_script:
  - docker build -t gradle-with-java9 .

script:
  - docker run -it -v $(pwd):/gradle -w /gradle gradle-with-java9 ./gradlew tasks --debug
